### ISSUE TITLE
Exposed Vias

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/TSL2561_Luminosity_Sensor_BOB#4]
Hey mike, I just saw this on a build come through production. It looks like your vias are 23 mil, and so the DRC has opened up the mask on all of them. Other than this minor problem the design looks fine.

Unless you'd like to take this quick rev, I think this could be handled by Patrick. 

Let us know and thanks!

**Comment by ToniCorinne** [comment]
Closing this as a non-issue until a future date when the board may be revised.
