### ISSUE TITLE
Filename mismatch

### ISSUE THREAD

**Issue by lutorm** [sparkfun/TSL2561_Luminosity_Sensor_BOB#6]
I used this repo a while ago for my TSL2561 and it worked fine, but now that I updated it seems the names of the source files have been changed from SFE_TSL2561.xxx to SparkFunTSL2561ArduinoLibrary.xxx. However, the cpp file still tries to include SFE_TSL2561.h, so now it doesn't compile. (Personally, I prefer the old names...)

I'm also confused why there are identical files in src/ and Libraries/Arduino/src/.

**Comment by ToniCorinne** [comment]
Sorry about that! We had to update all of our libraries for the new Arduino structure and this one got a bit messy with using git subtrees. The repo should be fixed now with all the proper files and the compilation errors have been removed. You can also download just the library [here](https://github.com/sparkfun/SparkFun_TSL2561_Arduino_Library).
