### ISSUE TITLE
Sensor saturation is not correctly detected, when integration time is less then 178ms. 

### ISSUE THREAD

**Issue by filippsudanov** [sparkfun/TSL2561_Luminosity_Sensor_BOB#7]
Currently saturation condition in the code is the following:
`	if ((CH0 == 0xFFFF) || (CH1 == 0xFFFF))`
but according to chip's datasheet this is valid only for integration time longer then 178ms. 

For tint = 101 ms saturated value is 37177 and for tint = 13.7ms it's 5047.

**Comment by Grahldg** [comment]
Thank you for your suggestion, unfortunately this product has been retired.  The repository will remain as a reference however we will no longer be maintaining it.  If you have any further questions about this product please consult our [forum](https://forum.sparkfun.com/).
